using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Data
{
    // reflette les roles de asp dans la base de donnée
    public class Roles
    {
        public string Id { get; set; }
        [Required(ErrorMessage = "{0} doit être remplie.")]
        [Display(Name = "Nom du rôle")]
        public string Name { get; set; }
        // sans compter les autogenerated field
    }
}
